workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH == "ci/gitlab-ci-typescript"

stages:
  - validate

.node_cache:
  cache:
    key:
      files:
        - package-lock.json
      prefix: "node${NODE_VERSION}"
    paths:
      - .npm/

typecheck:
  extends: .node_cache
  stage: validate
  parallel:
    matrix:
      - NODE_VERSION: ["20", "22"]
  image: node:${NODE_VERSION}-alpine
  script:
    - npm ci --cache .npm
    - npm run typecheck

test:
  extends: .node_cache
  stage: validate
  parallel:
    matrix:
      - NODE_VERSION: ["20", "22"]
  image: node:${NODE_VERSION}-alpine
  script:
    - npm ci --cache .npm
    - npm test
